'use client';

import { useState, useEffect } from 'react';
import { useGameStore } from '@/store/gameStore';
import { MINION_ROLES, type QuestPhase } from '@/types/game';
import { WowPanel, WowPanelInset, WowSectionHeader } from './WowPanel';
import { WowButton } from './WowButton';
import { WowInput } from './WowInput';
import { WowIcon, RoleIcon } from './WowIcon';
import { wowTheme } from '@/styles/theme';
import { getRandomEvent } from '@/lib/questSimulation';

const PHASE_LABELS: Record<QuestPhase, string> = {
  departure: 'Departing...',
  travel: 'Traveling...',
  work: 'Working...',
  event: 'Event!',
  resolution: 'Resolving...',
  return: 'Returning...',
  complete: 'Complete!',
};

const PHASE_COLORS: Record<QuestPhase, string> = {
  departure: wowTheme.colors.scribe,
  travel: '#06b6d4',
  work: wowTheme.colors.goldMid,
  event: wowTheme.colors.bronze,
  resolution: wowTheme.colors.scout,
  return: '#14b8a6',
  complete: wowTheme.colors.success,
};

// Simulated quest progression
function useQuestSimulation(questId: string | null) {
  const updateQuestPhase = useGameStore((state) => state.updateQuestPhase);
  const updateQuestProgress = useGameStore((state) => state.updateQuestProgress);
  const addQuestEvent = useGameStore((state) => state.addQuestEvent);
  const completeQuest = useGameStore((state) => state.completeQuest);
  const createArtifact = useGameStore((state) => state.createArtifact);
  const createPostcard = useGameStore((state) => state.createPostcard);
  const quests = useGameStore((state) => state.quests);
  const updateMinionState = useGameStore((state) => state.updateMinionState);

  const quest = quests.find((q) => q.id === questId);

  useEffect(() => {
    if (!quest || quest.phase === 'complete') return;

    const phases: QuestPhase[] = ['departure', 'travel', 'work', 'event', 'resolution', 'return', 'complete'];
    const currentPhaseIndex = phases.indexOf(quest.phase);

    // Progress within current phase
    const progressInterval = setInterval(() => {
      if (quest.progress < 100) {
        updateQuestProgress(quest.id, quest.progress + Math.random() * 5 + 2);
      }
    }, 500);

    // Phase transition
    const phaseTimeout = setTimeout(() => {
      if (quest.progress >= 100 && currentPhaseIndex < phases.length - 1) {
        const nextPhase = phases[currentPhaseIndex + 1];

        // Update minion state based on phase
        if (nextPhase === 'work') {
          updateMinionState(quest.minionId, 'working');
        } else if (nextPhase === 'return') {
          updateMinionState(quest.minionId, 'returning');
        }

        // Random events
        if (nextPhase === 'event' && Math.random() > 0.3) {
          const eventTypes: ('flavor' | 'modifier' | 'social')[] = ['flavor', 'modifier', 'social'];
          const weights = [0.6, 0.25, 0.15];
          const random = Math.random();
          let cumulative = 0;
          let selectedType: 'flavor' | 'modifier' | 'social' = 'flavor';
          for (let i = 0; i < weights.length; i++) {
            cumulative += weights[i];
            if (random < cumulative) {
              selectedType = eventTypes[i];
              break;
            }
          }
          addQuestEvent(quest.id, selectedType, getRandomEvent(selectedType));
        }

        if (nextPhase === 'complete') {
          // Create artifact
          const artifact = createArtifact(
            `Scroll of ${quest.title}`,
            'scroll',
            `Knowledge gathered from the quest: ${quest.title}`,
            `// Result of quest: ${quest.title}\n// Generated by ${quest.minionId}\n\nconst result = {\n  success: true,\n  data: "Quest completed successfully"\n};`,
            quest.id,
            quest.minionId,
            ['quest-result']
          );

          // Create postcard
          createPostcard(
            quest.id,
            quest.minionId,
            `Your minion ventured forth on a quest: "${quest.title}". Through determination and skill, they returned victorious, bearing the fruits of their labor.`,
            'Quest completed successfully!',
            [artifact.id]
          );

          completeQuest(quest.id);
        } else {
          updateQuestPhase(quest.id, nextPhase);
          updateQuestProgress(quest.id, 0);
        }
      }
    }, 3000 + Math.random() * 2000);

    return () => {
      clearInterval(progressInterval);
      clearTimeout(phaseTimeout);
    };
  }, [quest?.id, quest?.phase, quest?.progress]);
}

export function QuestPanel() {
  const minions = useGameStore((state) => state.minions);
  const quests = useGameStore((state) => state.quests);
  const activeQuestId = useGameStore((state) => state.activeQuestId);
  const selectedMinionId = useGameStore((state) => state.selectedMinionId);
  const createQuest = useGameStore((state) => state.createQuest);

  const [isCreating, setIsCreating] = useState(false);
  const [questTitle, setQuestTitle] = useState('');
  const [questDescription, setQuestDescription] = useState('');

  // Run quest simulation
  useQuestSimulation(activeQuestId);

  const activeQuest = quests.find((q) => q.id === activeQuestId);
  const selectedMinion = minions.find((m) => m.id === selectedMinionId);
  const availableMinions = minions.filter((m) => m.state === 'idle');

  const handleCreateQuest = () => {
    if (!questTitle.trim() || !selectedMinionId) return;
    createQuest(questTitle.trim(), questDescription.trim(), selectedMinionId);
    setQuestTitle('');
    setQuestDescription('');
    setIsCreating(false);
  };

  return (
    <WowPanel
      title="Quests"
      icon={<WowIcon name="quest" size="sm" />}
      className="w-80 animate-fade-in"
    >
      {activeQuest ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Active quest view */}
          <div>
            <h3 style={{
              fontWeight: 600,
              color: wowTheme.colors.goldLight,
              fontSize: wowTheme.fontSizes.lg,
              fontFamily: wowTheme.fonts.header,
              marginBottom: '8px',
            }}>
              {activeQuest.title}
            </h3>
            {activeQuest.description && (
              <p style={{
                fontSize: wowTheme.fontSizes.sm,
                color: wowTheme.colors.textSecondary,
                fontStyle: 'italic',
              }}>
                {activeQuest.description}
              </p>
            )}
          </div>

          {/* Phase indicator */}
          <WowPanelInset>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: '8px',
            }}>
              <span
                className="wow-badge"
                style={{
                  background: `linear-gradient(180deg, ${PHASE_COLORS[activeQuest.phase]} 0%, ${PHASE_COLORS[activeQuest.phase]}80 100%)`,
                  borderColor: PHASE_COLORS[activeQuest.phase],
                  color: wowTheme.colors.textPrimary,
                  boxShadow: `0 0 8px ${PHASE_COLORS[activeQuest.phase]}40`,
                }}
              >
                {PHASE_LABELS[activeQuest.phase]}
              </span>
              <span style={{
                fontSize: wowTheme.fontSizes.sm,
                color: wowTheme.colors.goldMid,
                fontWeight: 600,
              }}>
                {Math.round(activeQuest.progress)}%
              </span>
            </div>
            <div className="wow-progress">
              <div
                className="wow-progress-bar"
                style={{
                  width: `${activeQuest.progress}%`,
                  background: `linear-gradient(180deg, ${PHASE_COLORS[activeQuest.phase]} 0%, ${PHASE_COLORS[activeQuest.phase]}80 100%)`,
                }}
              />
            </div>
          </WowPanelInset>

          {/* Events log */}
          {activeQuest.events.length > 0 && (
            <div>
              <WowSectionHeader icon={<WowIcon name="scroll" size="xs" color={wowTheme.colors.goldMid} />}>
                Events
              </WowSectionHeader>
              <div style={{ maxHeight: '128px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                {activeQuest.events.map((event) => (
                  <div
                    key={event.id}
                    style={{
                      fontSize: wowTheme.fontSizes.xs,
                      padding: '8px',
                      borderRadius: wowTheme.radius.sm,
                      background: event.type === 'flavor'
                        ? wowTheme.colors.stoneDark
                        : event.type === 'modifier'
                        ? `${wowTheme.colors.bronze}20`
                        : `${wowTheme.colors.scribe}20`,
                      border: `1px solid ${
                        event.type === 'flavor'
                          ? wowTheme.colors.stoneBorder
                          : event.type === 'modifier'
                          ? wowTheme.colors.bronze
                          : wowTheme.colors.scribe
                      }`,
                      color: event.type === 'flavor'
                        ? wowTheme.colors.textMuted
                        : event.type === 'modifier'
                        ? wowTheme.colors.bronzeLight
                        : wowTheme.colors.scribeLight,
                    }}
                  >
                    {event.text}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : isCreating ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <WowInput
            label="Quest Title"
            value={questTitle}
            onChange={setQuestTitle}
            placeholder="e.g., Research API patterns"
          />
          <WowInput
            label="Description"
            value={questDescription}
            onChange={setQuestDescription}
            placeholder="What should the minion accomplish?"
            multiline
            rows={3}
          />

          {selectedMinion ? (
            <WowPanelInset>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <RoleIcon role={selectedMinion.role} size="sm" glow />
                <span style={{ color: wowTheme.colors.textPrimary, fontWeight: 500 }}>
                  {selectedMinion.name}
                </span>
                <span style={{ color: wowTheme.colors.textMuted, fontSize: wowTheme.fontSizes.xs }}>
                  will be dispatched
                </span>
              </div>
            </WowPanelInset>
          ) : (
            <p style={{
              color: wowTheme.colors.goldMid,
              fontSize: wowTheme.fontSizes.sm,
              fontStyle: 'italic',
            }}>
              Select an idle minion first
            </p>
          )}

          <div style={{ display: 'flex', gap: '8px' }}>
            <WowButton variant="secondary" onClick={() => setIsCreating(false)} fullWidth>
              Cancel
            </WowButton>
            <WowButton
              onClick={handleCreateQuest}
              disabled={!questTitle.trim() || !selectedMinion || selectedMinion.state !== 'idle'}
              fullWidth
            >
              Dispatch
            </WowButton>
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Recent quests */}
          <div style={{ maxHeight: '160px', overflowY: 'auto' }}>
            {quests.length === 0 ? (
              <WowPanelInset>
                <p style={{
                  textAlign: 'center',
                  color: wowTheme.colors.textMuted,
                  fontSize: wowTheme.fontSizes.sm,
                  padding: '16px 0',
                  fontStyle: 'italic',
                }}>
                  No quests yet. Create your first!
                </p>
              </WowPanelInset>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {quests
                  .slice()
                  .reverse()
                  .slice(0, 5)
                  .map((quest) => (
                    <div
                      key={quest.id}
                      className="wow-slot"
                      style={{ cursor: 'default' }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                        <span style={{
                          color: wowTheme.colors.textPrimary,
                          fontWeight: 500,
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                          flex: 1,
                        }}>
                          {quest.title}
                        </span>
                        <span
                          className="wow-badge"
                          style={{
                            marginLeft: '8px',
                            background: quest.phase === 'complete'
                              ? `${wowTheme.colors.success}30`
                              : `${wowTheme.colors.goldMid}30`,
                            borderColor: quest.phase === 'complete'
                              ? wowTheme.colors.success
                              : wowTheme.colors.goldMid,
                            color: quest.phase === 'complete'
                              ? wowTheme.colors.success
                              : wowTheme.colors.goldMid,
                          }}
                        >
                          {quest.phase === 'complete' ? 'Done' : 'Active'}
                        </span>
                      </div>
                    </div>
                  ))}
              </div>
            )}
          </div>

          <WowButton
            onClick={() => setIsCreating(true)}
            disabled={availableMinions.length === 0}
            fullWidth
            icon={<span style={{ fontSize: '14px' }}>+</span>}
          >
            {availableMinions.length === 0 ? 'No idle minions' : 'Create Quest'}
          </WowButton>
        </div>
      )}
    </WowPanel>
  );
}
